import type { VocabularyWord } from '@/types';

export const VOCABULARY_SEED: VocabularyWord[] = [
  // Animals
  {
    id: 'animal-cat',
    englishWord: 'Cat',
    mandarinWord: '猫',
    pinyin: 'māo',
    category: 'animals',
    imagePath: '/images/vocabulary/cat.png',
    audioEnPath: '/audio/en/cat.mp3',
    audioZhPath: '/audio/zh/mao.mp3',
    tags: ['pet', 'furry'],
  },
  {
    id: 'animal-dog',
    englishWord: 'Dog',
    mandarinWord: '狗',
    pinyin: 'gǒu',
    category: 'animals',
    imagePath: '/images/vocabulary/dog.png',
    audioEnPath: '/audio/en/dog.mp3',
    audioZhPath: '/audio/zh/gou.mp3',
    tags: ['pet', 'furry'],
  },
  {
    id: 'animal-rabbit',
    englishWord: 'Rabbit',
    mandarinWord: '兔子',
    pinyin: 'tùzi',
    category: 'animals',
    imagePath: '/images/vocabulary/rabbit.png',
    audioEnPath: '/audio/en/rabbit.mp3',
    audioZhPath: '/audio/zh/tuzi.mp3',
    tags: ['pet', 'fluffy'],
  },
  {
    id: 'animal-fish',
    englishWord: 'Fish',
    mandarinWord: '鱼',
    pinyin: 'yú',
    category: 'animals',
    imagePath: '/images/vocabulary/fish.png',
    audioEnPath: '/audio/en/fish.mp3',
    audioZhPath: '/audio/zh/yu.mp3',
    tags: ['water', 'swim'],
  },
  {
    id: 'animal-bird',
    englishWord: 'Bird',
    mandarinWord: '鸟',
    pinyin: 'niǎo',
    category: 'animals',
    imagePath: '/images/vocabulary/bird.png',
    audioEnPath: '/audio/en/bird.mp3',
    audioZhPath: '/audio/zh/niao.mp3',
    tags: ['fly', 'wing'],
  },
  // Food
  {
    id: 'food-apple',
    englishWord: 'Apple',
    mandarinWord: '苹果',
    pinyin: 'píngguǒ',
    category: 'food',
    imagePath: '/images/vocabulary/apple.png',
    audioEnPath: '/audio/en/apple.mp3',
    audioZhPath: '/audio/zh/pingguo.mp3',
    tags: ['fruit', 'red'],
  },
  {
    id: 'food-banana',
    englishWord: 'Banana',
    mandarinWord: '香蕉',
    pinyin: 'xiāngjiāo',
    category: 'food',
    imagePath: '/images/vocabulary/banana.png',
    audioEnPath: '/audio/en/banana.mp3',
    audioZhPath: '/audio/zh/xiangjiao.mp3',
    tags: ['fruit', 'yellow'],
  },
  {
    id: 'food-milk',
    englishWord: 'Milk',
    mandarinWord: '牛奶',
    pinyin: 'niúnǎi',
    category: 'food',
    imagePath: '/images/vocabulary/milk.png',
    audioEnPath: '/audio/en/milk.mp3',
    audioZhPath: '/audio/zh/niunai.mp3',
    tags: ['drink', 'white'],
  },
  {
    id: 'food-egg',
    englishWord: 'Egg',
    mandarinWord: '鸡蛋',
    pinyin: 'jīdàn',
    category: 'food',
    imagePath: '/images/vocabulary/egg.png',
    audioEnPath: '/audio/en/egg.mp3',
    audioZhPath: '/audio/zh/jidan.mp3',
    tags: ['protein', 'oval'],
  },
  {
    id: 'food-rice',
    englishWord: 'Rice',
    mandarinWord: '米饭',
    pinyin: 'mǐfàn',
    category: 'food',
    imagePath: '/images/vocabulary/rice.png',
    audioEnPath: '/audio/en/rice.mp3',
    audioZhPath: '/audio/zh/mifan.mp3',
    tags: ['grain', 'staple'],
  },
  // Colors
  {
    id: 'color-red',
    englishWord: 'Red',
    mandarinWord: '红色',
    pinyin: 'hóngsè',
    category: 'colors',
    imagePath: '/images/vocabulary/red.png',
    audioEnPath: '/audio/en/red.mp3',
    audioZhPath: '/audio/zh/hongse.mp3',
    tags: ['warm', 'bright'],
  },
  {
    id: 'color-blue',
    englishWord: 'Blue',
    mandarinWord: '蓝色',
    pinyin: 'lánsè',
    category: 'colors',
    imagePath: '/images/vocabulary/blue.png',
    audioEnPath: '/audio/en/blue.mp3',
    audioZhPath: '/audio/zh/lanse.mp3',
    tags: ['cool', 'sky'],
  },
  {
    id: 'color-yellow',
    englishWord: 'Yellow',
    mandarinWord: '黄色',
    pinyin: 'huángsè',
    category: 'colors',
    imagePath: '/images/vocabulary/yellow.png',
    audioEnPath: '/audio/en/yellow.mp3',
    audioZhPath: '/audio/zh/huangse.mp3',
    tags: ['warm', 'sun'],
  },
  {
    id: 'color-green',
    englishWord: 'Green',
    mandarinWord: '绿色',
    pinyin: 'lǜsè',
    category: 'colors',
    imagePath: '/images/vocabulary/green.png',
    audioEnPath: '/audio/en/green.mp3',
    audioZhPath: '/audio/zh/lvse.mp3',
    tags: ['nature', 'plant'],
  },
  {
    id: 'color-pink',
    englishWord: 'Pink',
    mandarinWord: '粉色',
    pinyin: 'fěnsè',
    category: 'colors',
    imagePath: '/images/vocabulary/pink.png',
    audioEnPath: '/audio/en/pink.mp3',
    audioZhPath: '/audio/zh/fense.mp3',
    tags: ['soft', 'light'],
  },
  // Body Parts
  {
    id: 'body-eyes',
    englishWord: 'Eyes',
    mandarinWord: '眼睛',
    pinyin: 'yǎnjīng',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/eyes.png',
    audioEnPath: '/audio/en/eyes.mp3',
    audioZhPath: '/audio/zh/yanjing.mp3',
    tags: ['face', 'see'],
  },
  {
    id: 'body-nose',
    englishWord: 'Nose',
    mandarinWord: '鼻子',
    pinyin: 'bízi',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/nose.png',
    audioEnPath: '/audio/en/nose.mp3',
    audioZhPath: '/audio/zh/bizi.mp3',
    tags: ['face', 'smell'],
  },
  {
    id: 'body-mouth',
    englishWord: 'Mouth',
    mandarinWord: '嘴巴',
    pinyin: 'zuǐba',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/mouth.png',
    audioEnPath: '/audio/en/mouth.mp3',
    audioZhPath: '/audio/zh/zuiba.mp3',
    tags: ['face', 'talk'],
  },
  {
    id: 'body-hand',
    englishWord: 'Hand',
    mandarinWord: '手',
    pinyin: 'shǒu',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/hand.png',
    audioEnPath: '/audio/en/hand.mp3',
    audioZhPath: '/audio/zh/shou.mp3',
    tags: ['limb', 'touch'],
  },
  {
    id: 'body-foot',
    englishWord: 'Foot',
    mandarinWord: '脚',
    pinyin: 'jiǎo',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/foot.png',
    audioEnPath: '/audio/en/foot.mp3',
    audioZhPath: '/audio/zh/jiao.mp3',
    tags: ['limb', 'walk'],
  },
];
