import type { VocabularyWord } from '../src/types/index';

export const FULL_VOCABULARY: VocabularyWord[] = [
  // ── Animals (15) ──────────────────────────────────────────────────────────
  {
    id: 'animal-cat',
    englishWord: 'Cat',
    mandarinWord: '猫',
    pinyin: 'māo',
    category: 'animals',
    imagePath: '/images/vocabulary/cat.png',
    audioEnPath: '/audio/en/cat.mp3',
    audioZhPath: '/audio/zh/cat.mp3',
    tags: [],
  },
  {
    id: 'animal-dog',
    englishWord: 'Dog',
    mandarinWord: '狗',
    pinyin: 'gǒu',
    category: 'animals',
    imagePath: '/images/vocabulary/dog.png',
    audioEnPath: '/audio/en/dog.mp3',
    audioZhPath: '/audio/zh/dog.mp3',
    tags: [],
  },
  {
    id: 'animal-rabbit',
    englishWord: 'Rabbit',
    mandarinWord: '兔子',
    pinyin: 'tùzi',
    category: 'animals',
    imagePath: '/images/vocabulary/rabbit.png',
    audioEnPath: '/audio/en/rabbit.mp3',
    audioZhPath: '/audio/zh/rabbit.mp3',
    tags: [],
  },
  {
    id: 'animal-fish',
    englishWord: 'Fish',
    mandarinWord: '鱼',
    pinyin: 'yú',
    category: 'animals',
    imagePath: '/images/vocabulary/fish.png',
    audioEnPath: '/audio/en/fish.mp3',
    audioZhPath: '/audio/zh/fish.mp3',
    tags: [],
  },
  {
    id: 'animal-bird',
    englishWord: 'Bird',
    mandarinWord: '鸟',
    pinyin: 'niǎo',
    category: 'animals',
    imagePath: '/images/vocabulary/bird.png',
    audioEnPath: '/audio/en/bird.mp3',
    audioZhPath: '/audio/zh/bird.mp3',
    tags: [],
  },
  {
    id: 'animal-duck',
    englishWord: 'Duck',
    mandarinWord: '鸭子',
    pinyin: 'yāzi',
    category: 'animals',
    imagePath: '/images/vocabulary/duck.png',
    audioEnPath: '/audio/en/duck.mp3',
    audioZhPath: '/audio/zh/duck.mp3',
    tags: [],
  },
  {
    id: 'animal-elephant',
    englishWord: 'Elephant',
    mandarinWord: '大象',
    pinyin: 'dàxiàng',
    category: 'animals',
    imagePath: '/images/vocabulary/elephant.png',
    audioEnPath: '/audio/en/elephant.mp3',
    audioZhPath: '/audio/zh/elephant.mp3',
    tags: [],
  },
  {
    id: 'animal-monkey',
    englishWord: 'Monkey',
    mandarinWord: '猴子',
    pinyin: 'hóuzi',
    category: 'animals',
    imagePath: '/images/vocabulary/monkey.png',
    audioEnPath: '/audio/en/monkey.mp3',
    audioZhPath: '/audio/zh/monkey.mp3',
    tags: [],
  },
  {
    id: 'animal-panda',
    englishWord: 'Panda',
    mandarinWord: '熊猫',
    pinyin: 'xióngmāo',
    category: 'animals',
    imagePath: '/images/vocabulary/panda.png',
    audioEnPath: '/audio/en/panda.mp3',
    audioZhPath: '/audio/zh/panda.mp3',
    tags: [],
  },
  {
    id: 'animal-tiger',
    englishWord: 'Tiger',
    mandarinWord: '老虎',
    pinyin: 'lǎohǔ',
    category: 'animals',
    imagePath: '/images/vocabulary/tiger.png',
    audioEnPath: '/audio/en/tiger.mp3',
    audioZhPath: '/audio/zh/tiger.mp3',
    tags: [],
  },
  {
    id: 'animal-horse',
    englishWord: 'Horse',
    mandarinWord: '马',
    pinyin: 'mǎ',
    category: 'animals',
    imagePath: '/images/vocabulary/horse.png',
    audioEnPath: '/audio/en/horse.mp3',
    audioZhPath: '/audio/zh/horse.mp3',
    tags: [],
  },
  {
    id: 'animal-cow',
    englishWord: 'Cow',
    mandarinWord: '牛',
    pinyin: 'niú',
    category: 'animals',
    imagePath: '/images/vocabulary/cow.png',
    audioEnPath: '/audio/en/cow.mp3',
    audioZhPath: '/audio/zh/cow.mp3',
    tags: [],
  },
  {
    id: 'animal-frog',
    englishWord: 'Frog',
    mandarinWord: '青蛙',
    pinyin: 'qīngwā',
    category: 'animals',
    imagePath: '/images/vocabulary/frog.png',
    audioEnPath: '/audio/en/frog.mp3',
    audioZhPath: '/audio/zh/frog.mp3',
    tags: [],
  },
  {
    id: 'animal-bee',
    englishWord: 'Bee',
    mandarinWord: '蜜蜂',
    pinyin: 'mìfēng',
    category: 'animals',
    imagePath: '/images/vocabulary/bee.png',
    audioEnPath: '/audio/en/bee.mp3',
    audioZhPath: '/audio/zh/bee.mp3',
    tags: [],
  },
  {
    id: 'animal-butterfly',
    englishWord: 'Butterfly',
    mandarinWord: '蝴蝶',
    pinyin: 'húdié',
    category: 'animals',
    imagePath: '/images/vocabulary/butterfly.png',
    audioEnPath: '/audio/en/butterfly.mp3',
    audioZhPath: '/audio/zh/butterfly.mp3',
    tags: [],
  },

  // ── Food (15) ─────────────────────────────────────────────────────────────
  {
    id: 'food-apple',
    englishWord: 'Apple',
    mandarinWord: '苹果',
    pinyin: 'píngguǒ',
    category: 'food',
    imagePath: '/images/vocabulary/apple.png',
    audioEnPath: '/audio/en/apple.mp3',
    audioZhPath: '/audio/zh/apple.mp3',
    tags: [],
  },
  {
    id: 'food-banana',
    englishWord: 'Banana',
    mandarinWord: '香蕉',
    pinyin: 'xiāngjiāo',
    category: 'food',
    imagePath: '/images/vocabulary/banana.png',
    audioEnPath: '/audio/en/banana.mp3',
    audioZhPath: '/audio/zh/banana.mp3',
    tags: [],
  },
  {
    id: 'food-orange',
    englishWord: 'Orange',
    mandarinWord: '橙子',
    pinyin: 'chéngzi',
    category: 'food',
    imagePath: '/images/vocabulary/orange.png',
    audioEnPath: '/audio/en/orange.mp3',
    audioZhPath: '/audio/zh/orange.mp3',
    tags: [],
  },
  {
    id: 'food-milk',
    englishWord: 'Milk',
    mandarinWord: '牛奶',
    pinyin: 'niúnǎi',
    category: 'food',
    imagePath: '/images/vocabulary/milk.png',
    audioEnPath: '/audio/en/milk.mp3',
    audioZhPath: '/audio/zh/milk.mp3',
    tags: [],
  },
  {
    id: 'food-egg',
    englishWord: 'Egg',
    mandarinWord: '鸡蛋',
    pinyin: 'jīdàn',
    category: 'food',
    imagePath: '/images/vocabulary/egg.png',
    audioEnPath: '/audio/en/egg.mp3',
    audioZhPath: '/audio/zh/egg.mp3',
    tags: [],
  },
  {
    id: 'food-rice',
    englishWord: 'Rice',
    mandarinWord: '米饭',
    pinyin: 'mǐfàn',
    category: 'food',
    imagePath: '/images/vocabulary/rice.png',
    audioEnPath: '/audio/en/rice.mp3',
    audioZhPath: '/audio/zh/rice.mp3',
    tags: [],
  },
  {
    id: 'food-bread',
    englishWord: 'Bread',
    mandarinWord: '面包',
    pinyin: 'miànbāo',
    category: 'food',
    imagePath: '/images/vocabulary/bread.png',
    audioEnPath: '/audio/en/bread.mp3',
    audioZhPath: '/audio/zh/bread.mp3',
    tags: [],
  },
  {
    id: 'food-cake',
    englishWord: 'Cake',
    mandarinWord: '蛋糕',
    pinyin: 'dàngāo',
    category: 'food',
    imagePath: '/images/vocabulary/cake.png',
    audioEnPath: '/audio/en/cake.mp3',
    audioZhPath: '/audio/zh/cake.mp3',
    tags: [],
  },
  {
    id: 'food-water',
    englishWord: 'Water',
    mandarinWord: '水',
    pinyin: 'shuǐ',
    category: 'food',
    imagePath: '/images/vocabulary/water.png',
    audioEnPath: '/audio/en/water.mp3',
    audioZhPath: '/audio/zh/water.mp3',
    tags: [],
  },
  {
    id: 'food-juice',
    englishWord: 'Juice',
    mandarinWord: '果汁',
    pinyin: 'guǒzhī',
    category: 'food',
    imagePath: '/images/vocabulary/juice.png',
    audioEnPath: '/audio/en/juice.mp3',
    audioZhPath: '/audio/zh/juice.mp3',
    tags: [],
  },
  {
    id: 'food-cookie',
    englishWord: 'Cookie',
    mandarinWord: '饼干',
    pinyin: 'bǐnggān',
    category: 'food',
    imagePath: '/images/vocabulary/cookie.png',
    audioEnPath: '/audio/en/cookie.mp3',
    audioZhPath: '/audio/zh/cookie.mp3',
    tags: [],
  },
  {
    id: 'food-noodles',
    englishWord: 'Noodles',
    mandarinWord: '面条',
    pinyin: 'miàntiáo',
    category: 'food',
    imagePath: '/images/vocabulary/noodles.png',
    audioEnPath: '/audio/en/noodles.mp3',
    audioZhPath: '/audio/zh/noodles.mp3',
    tags: [],
  },
  {
    id: 'food-tofu',
    englishWord: 'Tofu',
    mandarinWord: '豆腐',
    pinyin: 'dòufu',
    category: 'food',
    imagePath: '/images/vocabulary/tofu.png',
    audioEnPath: '/audio/en/tofu.mp3',
    audioZhPath: '/audio/zh/tofu.mp3',
    tags: [],
  },
  {
    id: 'food-mango',
    englishWord: 'Mango',
    mandarinWord: '芒果',
    pinyin: 'mángguǒ',
    category: 'food',
    imagePath: '/images/vocabulary/mango.png',
    audioEnPath: '/audio/en/mango.mp3',
    audioZhPath: '/audio/zh/mango.mp3',
    tags: [],
  },
  {
    id: 'food-strawberry',
    englishWord: 'Strawberry',
    mandarinWord: '草莓',
    pinyin: 'cǎoméi',
    category: 'food',
    imagePath: '/images/vocabulary/strawberry.png',
    audioEnPath: '/audio/en/strawberry.mp3',
    audioZhPath: '/audio/zh/strawberry.mp3',
    tags: [],
  },

  // ── Colors (10) ───────────────────────────────────────────────────────────
  {
    id: 'color-red',
    englishWord: 'Red',
    mandarinWord: '红色',
    pinyin: 'hóngsè',
    category: 'colors',
    imagePath: '/images/vocabulary/red.png',
    audioEnPath: '/audio/en/red.mp3',
    audioZhPath: '/audio/zh/red.mp3',
    tags: [],
  },
  {
    id: 'color-blue',
    englishWord: 'Blue',
    mandarinWord: '蓝色',
    pinyin: 'lánsè',
    category: 'colors',
    imagePath: '/images/vocabulary/blue.png',
    audioEnPath: '/audio/en/blue.mp3',
    audioZhPath: '/audio/zh/blue.mp3',
    tags: [],
  },
  {
    id: 'color-yellow',
    englishWord: 'Yellow',
    mandarinWord: '黄色',
    pinyin: 'huángsè',
    category: 'colors',
    imagePath: '/images/vocabulary/yellow.png',
    audioEnPath: '/audio/en/yellow.mp3',
    audioZhPath: '/audio/zh/yellow.mp3',
    tags: [],
  },
  {
    id: 'color-green',
    englishWord: 'Green',
    mandarinWord: '绿色',
    pinyin: 'lǜsè',
    category: 'colors',
    imagePath: '/images/vocabulary/green.png',
    audioEnPath: '/audio/en/green.mp3',
    audioZhPath: '/audio/zh/green.mp3',
    tags: [],
  },
  {
    id: 'color-pink',
    englishWord: 'Pink',
    mandarinWord: '粉色',
    pinyin: 'fěnsè',
    category: 'colors',
    imagePath: '/images/vocabulary/pink.png',
    audioEnPath: '/audio/en/pink.mp3',
    audioZhPath: '/audio/zh/pink.mp3',
    tags: [],
  },
  {
    id: 'color-purple',
    englishWord: 'Purple',
    mandarinWord: '紫色',
    pinyin: 'zǐsè',
    category: 'colors',
    imagePath: '/images/vocabulary/purple.png',
    audioEnPath: '/audio/en/purple.mp3',
    audioZhPath: '/audio/zh/purple.mp3',
    tags: [],
  },
  {
    id: 'color-orange',
    englishWord: 'Orange',
    mandarinWord: '橙色',
    pinyin: 'chéngsè',
    category: 'colors',
    imagePath: '/images/vocabulary/orange-color.png',
    audioEnPath: '/audio/en/orange-color.mp3',
    audioZhPath: '/audio/zh/orange-color.mp3',
    tags: [],
  },
  {
    id: 'color-white',
    englishWord: 'White',
    mandarinWord: '白色',
    pinyin: 'báisè',
    category: 'colors',
    imagePath: '/images/vocabulary/white.png',
    audioEnPath: '/audio/en/white.mp3',
    audioZhPath: '/audio/zh/white.mp3',
    tags: [],
  },
  {
    id: 'color-black',
    englishWord: 'Black',
    mandarinWord: '黑色',
    pinyin: 'hēisè',
    category: 'colors',
    imagePath: '/images/vocabulary/black.png',
    audioEnPath: '/audio/en/black.mp3',
    audioZhPath: '/audio/zh/black.mp3',
    tags: [],
  },
  {
    id: 'color-brown',
    englishWord: 'Brown',
    mandarinWord: '棕色',
    pinyin: 'zōngsè',
    category: 'colors',
    imagePath: '/images/vocabulary/brown.png',
    audioEnPath: '/audio/en/brown.mp3',
    audioZhPath: '/audio/zh/brown.mp3',
    tags: [],
  },

  // ── Body Parts (10) ───────────────────────────────────────────────────────
  {
    id: 'body-eyes',
    englishWord: 'Eyes',
    mandarinWord: '眼睛',
    pinyin: 'yǎnjīng',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/eyes.png',
    audioEnPath: '/audio/en/eyes.mp3',
    audioZhPath: '/audio/zh/eyes.mp3',
    tags: [],
  },
  {
    id: 'body-nose',
    englishWord: 'Nose',
    mandarinWord: '鼻子',
    pinyin: 'bízi',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/nose.png',
    audioEnPath: '/audio/en/nose.mp3',
    audioZhPath: '/audio/zh/nose.mp3',
    tags: [],
  },
  {
    id: 'body-mouth',
    englishWord: 'Mouth',
    mandarinWord: '嘴巴',
    pinyin: 'zuǐba',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/mouth.png',
    audioEnPath: '/audio/en/mouth.mp3',
    audioZhPath: '/audio/zh/mouth.mp3',
    tags: [],
  },
  {
    id: 'body-ears',
    englishWord: 'Ears',
    mandarinWord: '耳朵',
    pinyin: 'ěrduo',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/ears.png',
    audioEnPath: '/audio/en/ears.mp3',
    audioZhPath: '/audio/zh/ears.mp3',
    tags: [],
  },
  {
    id: 'body-hand',
    englishWord: 'Hand',
    mandarinWord: '手',
    pinyin: 'shǒu',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/hand.png',
    audioEnPath: '/audio/en/hand.mp3',
    audioZhPath: '/audio/zh/hand.mp3',
    tags: [],
  },
  {
    id: 'body-foot',
    englishWord: 'Foot',
    mandarinWord: '脚',
    pinyin: 'jiǎo',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/foot.png',
    audioEnPath: '/audio/en/foot.mp3',
    audioZhPath: '/audio/zh/foot.mp3',
    tags: [],
  },
  {
    id: 'body-head',
    englishWord: 'Head',
    mandarinWord: '头',
    pinyin: 'tóu',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/head.png',
    audioEnPath: '/audio/en/head.mp3',
    audioZhPath: '/audio/zh/head.mp3',
    tags: [],
  },
  {
    id: 'body-tummy',
    englishWord: 'Tummy',
    mandarinWord: '肚子',
    pinyin: 'dùzi',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/tummy.png',
    audioEnPath: '/audio/en/tummy.mp3',
    audioZhPath: '/audio/zh/tummy.mp3',
    tags: [],
  },
  {
    id: 'body-fingers',
    englishWord: 'Fingers',
    mandarinWord: '手指',
    pinyin: 'shǒuzhǐ',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/fingers.png',
    audioEnPath: '/audio/en/fingers.mp3',
    audioZhPath: '/audio/zh/fingers.mp3',
    tags: [],
  },
  {
    id: 'body-hair',
    englishWord: 'Hair',
    mandarinWord: '头发',
    pinyin: 'tóufa',
    category: 'bodyParts',
    imagePath: '/images/vocabulary/hair.png',
    audioEnPath: '/audio/en/hair.mp3',
    audioZhPath: '/audio/zh/hair.mp3',
    tags: [],
  },

  // ── Family (10) ───────────────────────────────────────────────────────────
  {
    id: 'family-mama',
    englishWord: 'Mama',
    mandarinWord: '妈妈',
    pinyin: 'māma',
    category: 'family',
    imagePath: '/images/vocabulary/mama.png',
    audioEnPath: '/audio/en/mama.mp3',
    audioZhPath: '/audio/zh/mama.mp3',
    tags: [],
  },
  {
    id: 'family-baba',
    englishWord: 'Baba',
    mandarinWord: '爸爸',
    pinyin: 'bàba',
    category: 'family',
    imagePath: '/images/vocabulary/baba.png',
    audioEnPath: '/audio/en/baba.mp3',
    audioZhPath: '/audio/zh/baba.mp3',
    tags: [],
  },
  {
    id: 'family-baby',
    englishWord: 'Baby',
    mandarinWord: '宝宝',
    pinyin: 'bǎobao',
    category: 'family',
    imagePath: '/images/vocabulary/baby.png',
    audioEnPath: '/audio/en/baby.mp3',
    audioZhPath: '/audio/zh/baby.mp3',
    tags: [],
  },
  {
    id: 'family-grandma',
    englishWord: 'Grandma',
    mandarinWord: '奶奶',
    pinyin: 'nǎinai',
    category: 'family',
    imagePath: '/images/vocabulary/grandma.png',
    audioEnPath: '/audio/en/grandma.mp3',
    audioZhPath: '/audio/zh/grandma.mp3',
    tags: [],
  },
  {
    id: 'family-grandpa',
    englishWord: 'Grandpa',
    mandarinWord: '爷爷',
    pinyin: 'yéye',
    category: 'family',
    imagePath: '/images/vocabulary/grandpa.png',
    audioEnPath: '/audio/en/grandpa.mp3',
    audioZhPath: '/audio/zh/grandpa.mp3',
    tags: [],
  },
  {
    id: 'family-sister',
    englishWord: 'Sister',
    mandarinWord: '姐姐',
    pinyin: 'jiějie',
    category: 'family',
    imagePath: '/images/vocabulary/sister.png',
    audioEnPath: '/audio/en/sister.mp3',
    audioZhPath: '/audio/zh/sister.mp3',
    tags: [],
  },
  {
    id: 'family-brother',
    englishWord: 'Brother',
    mandarinWord: '哥哥',
    pinyin: 'gēge',
    category: 'family',
    imagePath: '/images/vocabulary/brother.png',
    audioEnPath: '/audio/en/brother.mp3',
    audioZhPath: '/audio/zh/brother.mp3',
    tags: [],
  },
  {
    id: 'family-family',
    englishWord: 'Family',
    mandarinWord: '家人',
    pinyin: 'jiārén',
    category: 'family',
    imagePath: '/images/vocabulary/family.png',
    audioEnPath: '/audio/en/family.mp3',
    audioZhPath: '/audio/zh/family.mp3',
    tags: [],
  },
  {
    id: 'family-love',
    englishWord: 'Love',
    mandarinWord: '爱',
    pinyin: 'ài',
    category: 'family',
    imagePath: '/images/vocabulary/love.png',
    audioEnPath: '/audio/en/love.mp3',
    audioZhPath: '/audio/zh/love.mp3',
    tags: [],
  },
  {
    id: 'family-hug',
    englishWord: 'Hug',
    mandarinWord: '抱抱',
    pinyin: 'bàobào',
    category: 'family',
    imagePath: '/images/vocabulary/hug.png',
    audioEnPath: '/audio/en/hug.mp3',
    audioZhPath: '/audio/zh/hug.mp3',
    tags: [],
  },

  // ── Objects (20) ──────────────────────────────────────────────────────────
  {
    id: 'object-ball',
    englishWord: 'Ball',
    mandarinWord: '球',
    pinyin: 'qiú',
    category: 'objects',
    imagePath: '/images/vocabulary/ball.png',
    audioEnPath: '/audio/en/ball.mp3',
    audioZhPath: '/audio/zh/ball.mp3',
    tags: [],
  },
  {
    id: 'object-book',
    englishWord: 'Book',
    mandarinWord: '书',
    pinyin: 'shū',
    category: 'objects',
    imagePath: '/images/vocabulary/book.png',
    audioEnPath: '/audio/en/book.mp3',
    audioZhPath: '/audio/zh/book.mp3',
    tags: [],
  },
  {
    id: 'object-chair',
    englishWord: 'Chair',
    mandarinWord: '椅子',
    pinyin: 'yǐzi',
    category: 'objects',
    imagePath: '/images/vocabulary/chair.png',
    audioEnPath: '/audio/en/chair.mp3',
    audioZhPath: '/audio/zh/chair.mp3',
    tags: [],
  },
  {
    id: 'object-table',
    englishWord: 'Table',
    mandarinWord: '桌子',
    pinyin: 'zhuōzi',
    category: 'objects',
    imagePath: '/images/vocabulary/table.png',
    audioEnPath: '/audio/en/table.mp3',
    audioZhPath: '/audio/zh/table.mp3',
    tags: [],
  },
  {
    id: 'object-cup',
    englishWord: 'Cup',
    mandarinWord: '杯子',
    pinyin: 'bēizi',
    category: 'objects',
    imagePath: '/images/vocabulary/cup.png',
    audioEnPath: '/audio/en/cup.mp3',
    audioZhPath: '/audio/zh/cup.mp3',
    tags: [],
  },
  {
    id: 'object-bag',
    englishWord: 'Bag',
    mandarinWord: '包包',
    pinyin: 'bāobao',
    category: 'objects',
    imagePath: '/images/vocabulary/bag.png',
    audioEnPath: '/audio/en/bag.mp3',
    audioZhPath: '/audio/zh/bag.mp3',
    tags: [],
  },
  {
    id: 'object-car',
    englishWord: 'Car',
    mandarinWord: '汽车',
    pinyin: 'qìchē',
    category: 'objects',
    imagePath: '/images/vocabulary/car.png',
    audioEnPath: '/audio/en/car.mp3',
    audioZhPath: '/audio/zh/car.mp3',
    tags: [],
  },
  {
    id: 'object-bed',
    englishWord: 'Bed',
    mandarinWord: '床',
    pinyin: 'chuáng',
    category: 'objects',
    imagePath: '/images/vocabulary/bed.png',
    audioEnPath: '/audio/en/bed.mp3',
    audioZhPath: '/audio/zh/bed.mp3',
    tags: [],
  },
  {
    id: 'object-door',
    englishWord: 'Door',
    mandarinWord: '门',
    pinyin: 'mén',
    category: 'objects',
    imagePath: '/images/vocabulary/door.png',
    audioEnPath: '/audio/en/door.mp3',
    audioZhPath: '/audio/zh/door.mp3',
    tags: [],
  },
  {
    id: 'object-window',
    englishWord: 'Window',
    mandarinWord: '窗户',
    pinyin: 'chuānghu',
    category: 'objects',
    imagePath: '/images/vocabulary/window.png',
    audioEnPath: '/audio/en/window.mp3',
    audioZhPath: '/audio/zh/window.mp3',
    tags: [],
  },
  {
    id: 'object-pencil',
    englishWord: 'Pencil',
    mandarinWord: '铅笔',
    pinyin: 'qiānbǐ',
    category: 'objects',
    imagePath: '/images/vocabulary/pencil.png',
    audioEnPath: '/audio/en/pencil.mp3',
    audioZhPath: '/audio/zh/pencil.mp3',
    tags: [],
  },
  {
    id: 'object-star',
    englishWord: 'Star',
    mandarinWord: '星星',
    pinyin: 'xīngxīng',
    category: 'objects',
    imagePath: '/images/vocabulary/star.png',
    audioEnPath: '/audio/en/star.mp3',
    audioZhPath: '/audio/zh/star.mp3',
    tags: [],
  },
  {
    id: 'object-moon',
    englishWord: 'Moon',
    mandarinWord: '月亮',
    pinyin: 'yuèliang',
    category: 'objects',
    imagePath: '/images/vocabulary/moon.png',
    audioEnPath: '/audio/en/moon.mp3',
    audioZhPath: '/audio/zh/moon.mp3',
    tags: [],
  },
  {
    id: 'object-sun',
    englishWord: 'Sun',
    mandarinWord: '太阳',
    pinyin: 'tàiyáng',
    category: 'objects',
    imagePath: '/images/vocabulary/sun.png',
    audioEnPath: '/audio/en/sun.mp3',
    audioZhPath: '/audio/zh/sun.mp3',
    tags: [],
  },
  {
    id: 'object-flower',
    englishWord: 'Flower',
    mandarinWord: '花',
    pinyin: 'huā',
    category: 'objects',
    imagePath: '/images/vocabulary/flower.png',
    audioEnPath: '/audio/en/flower.mp3',
    audioZhPath: '/audio/zh/flower.mp3',
    tags: [],
  },
  {
    id: 'object-tree',
    englishWord: 'Tree',
    mandarinWord: '树',
    pinyin: 'shù',
    category: 'objects',
    imagePath: '/images/vocabulary/tree.png',
    audioEnPath: '/audio/en/tree.mp3',
    audioZhPath: '/audio/zh/tree.mp3',
    tags: [],
  },
  {
    id: 'object-house',
    englishWord: 'House',
    mandarinWord: '房子',
    pinyin: 'fángzi',
    category: 'objects',
    imagePath: '/images/vocabulary/house.png',
    audioEnPath: '/audio/en/house.mp3',
    audioZhPath: '/audio/zh/house.mp3',
    tags: [],
  },
  {
    id: 'object-clock',
    englishWord: 'Clock',
    mandarinWord: '时钟',
    pinyin: 'shízhōng',
    category: 'objects',
    imagePath: '/images/vocabulary/clock.png',
    audioEnPath: '/audio/en/clock.mp3',
    audioZhPath: '/audio/zh/clock.mp3',
    tags: [],
  },
  {
    id: 'object-umbrella',
    englishWord: 'Umbrella',
    mandarinWord: '雨伞',
    pinyin: 'yǔsǎn',
    category: 'objects',
    imagePath: '/images/vocabulary/umbrella.png',
    audioEnPath: '/audio/en/umbrella.mp3',
    audioZhPath: '/audio/zh/umbrella.mp3',
    tags: [],
  },
  {
    id: 'object-hat',
    englishWord: 'Hat',
    mandarinWord: '帽子',
    pinyin: 'màozi',
    category: 'objects',
    imagePath: '/images/vocabulary/hat.png',
    audioEnPath: '/audio/en/hat.mp3',
    audioZhPath: '/audio/zh/hat.mp3',
    tags: [],
  },

  // ── Actions / Greetings (20) ───────────────────────────────────────────────
  {
    id: 'action-hello',
    englishWord: 'Hello',
    mandarinWord: '你好',
    pinyin: 'nǐhǎo',
    category: 'actions',
    imagePath: '/images/vocabulary/hello.png',
    audioEnPath: '/audio/en/hello.mp3',
    audioZhPath: '/audio/zh/hello.mp3',
    tags: [],
  },
  {
    id: 'action-goodbye',
    englishWord: 'Goodbye',
    mandarinWord: '再见',
    pinyin: 'zàijiàn',
    category: 'actions',
    imagePath: '/images/vocabulary/goodbye.png',
    audioEnPath: '/audio/en/goodbye.mp3',
    audioZhPath: '/audio/zh/goodbye.mp3',
    tags: [],
  },
  {
    id: 'action-thank-you',
    englishWord: 'Thank You',
    mandarinWord: '谢谢',
    pinyin: 'xièxiè',
    category: 'actions',
    imagePath: '/images/vocabulary/thank-you.png',
    audioEnPath: '/audio/en/thank-you.mp3',
    audioZhPath: '/audio/zh/thank-you.mp3',
    tags: [],
  },
  {
    id: 'action-please',
    englishWord: 'Please',
    mandarinWord: '请',
    pinyin: 'qǐng',
    category: 'actions',
    imagePath: '/images/vocabulary/please.png',
    audioEnPath: '/audio/en/please.mp3',
    audioZhPath: '/audio/zh/please.mp3',
    tags: [],
  },
  {
    id: 'action-yes',
    englishWord: 'Yes',
    mandarinWord: '是的',
    pinyin: 'shì de',
    category: 'actions',
    imagePath: '/images/vocabulary/yes.png',
    audioEnPath: '/audio/en/yes.mp3',
    audioZhPath: '/audio/zh/yes.mp3',
    tags: [],
  },
  {
    id: 'action-no',
    englishWord: 'No',
    mandarinWord: '不是',
    pinyin: 'bú shì',
    category: 'actions',
    imagePath: '/images/vocabulary/no.png',
    audioEnPath: '/audio/en/no.mp3',
    audioZhPath: '/audio/zh/no.mp3',
    tags: [],
  },
  {
    id: 'action-run',
    englishWord: 'Run',
    mandarinWord: '跑',
    pinyin: 'pǎo',
    category: 'actions',
    imagePath: '/images/vocabulary/run.png',
    audioEnPath: '/audio/en/run.mp3',
    audioZhPath: '/audio/zh/run.mp3',
    tags: [],
  },
  {
    id: 'action-jump',
    englishWord: 'Jump',
    mandarinWord: '跳',
    pinyin: 'tiào',
    category: 'actions',
    imagePath: '/images/vocabulary/jump.png',
    audioEnPath: '/audio/en/jump.mp3',
    audioZhPath: '/audio/zh/jump.mp3',
    tags: [],
  },
  {
    id: 'action-eat',
    englishWord: 'Eat',
    mandarinWord: '吃',
    pinyin: 'chī',
    category: 'actions',
    imagePath: '/images/vocabulary/eat.png',
    audioEnPath: '/audio/en/eat.mp3',
    audioZhPath: '/audio/zh/eat.mp3',
    tags: [],
  },
  {
    id: 'action-drink',
    englishWord: 'Drink',
    mandarinWord: '喝',
    pinyin: 'hē',
    category: 'actions',
    imagePath: '/images/vocabulary/drink.png',
    audioEnPath: '/audio/en/drink.mp3',
    audioZhPath: '/audio/zh/drink.mp3',
    tags: [],
  },
  {
    id: 'action-sleep',
    englishWord: 'Sleep',
    mandarinWord: '睡觉',
    pinyin: 'shuìjiào',
    category: 'actions',
    imagePath: '/images/vocabulary/sleep.png',
    audioEnPath: '/audio/en/sleep.mp3',
    audioZhPath: '/audio/zh/sleep.mp3',
    tags: [],
  },
  {
    id: 'action-play',
    englishWord: 'Play',
    mandarinWord: '玩',
    pinyin: 'wán',
    category: 'actions',
    imagePath: '/images/vocabulary/play.png',
    audioEnPath: '/audio/en/play.mp3',
    audioZhPath: '/audio/zh/play.mp3',
    tags: [],
  },
  {
    id: 'action-sit',
    englishWord: 'Sit',
    mandarinWord: '坐',
    pinyin: 'zuò',
    category: 'actions',
    imagePath: '/images/vocabulary/sit.png',
    audioEnPath: '/audio/en/sit.mp3',
    audioZhPath: '/audio/zh/sit.mp3',
    tags: [],
  },
  {
    id: 'action-stand',
    englishWord: 'Stand',
    mandarinWord: '站',
    pinyin: 'zhàn',
    category: 'actions',
    imagePath: '/images/vocabulary/stand.png',
    audioEnPath: '/audio/en/stand.mp3',
    audioZhPath: '/audio/zh/stand.mp3',
    tags: [],
  },
  {
    id: 'action-open',
    englishWord: 'Open',
    mandarinWord: '开',
    pinyin: 'kāi',
    category: 'actions',
    imagePath: '/images/vocabulary/open.png',
    audioEnPath: '/audio/en/open.mp3',
    audioZhPath: '/audio/zh/open.mp3',
    tags: [],
  },
  {
    id: 'action-close',
    englishWord: 'Close',
    mandarinWord: '关',
    pinyin: 'guān',
    category: 'actions',
    imagePath: '/images/vocabulary/close.png',
    audioEnPath: '/audio/en/close.mp3',
    audioZhPath: '/audio/zh/close.mp3',
    tags: [],
  },
  {
    id: 'action-wash',
    englishWord: 'Wash',
    mandarinWord: '洗',
    pinyin: 'xǐ',
    category: 'actions',
    imagePath: '/images/vocabulary/wash.png',
    audioEnPath: '/audio/en/wash.mp3',
    audioZhPath: '/audio/zh/wash.mp3',
    tags: [],
  },
  {
    id: 'action-cry',
    englishWord: 'Cry',
    mandarinWord: '哭',
    pinyin: 'kū',
    category: 'actions',
    imagePath: '/images/vocabulary/cry.png',
    audioEnPath: '/audio/en/cry.mp3',
    audioZhPath: '/audio/zh/cry.mp3',
    tags: [],
  },
  {
    id: 'action-laugh',
    englishWord: 'Laugh',
    mandarinWord: '笑',
    pinyin: 'xiào',
    category: 'actions',
    imagePath: '/images/vocabulary/laugh.png',
    audioEnPath: '/audio/en/laugh.mp3',
    audioZhPath: '/audio/zh/laugh.mp3',
    tags: [],
  },
  {
    id: 'action-dance',
    englishWord: 'Dance',
    mandarinWord: '跳舞',
    pinyin: 'tiàowǔ',
    category: 'actions',
    imagePath: '/images/vocabulary/dance.png',
    audioEnPath: '/audio/en/dance.mp3',
    audioZhPath: '/audio/zh/dance.mp3',
    tags: [],
  },
];
